### ISSUE TITLE
How the locations are stored in the Link class is redundant

### ISSUE THREAD

**Issue by nt314p** [nt314p/Zork#22]
A Link stores only two locations. These two locations are currently being stored in a HashMap, with a key being a location and its value being a location. 

Let's call the location key "a" and the location value "b".

If we want to grab b from the link, we just input a to the HashMap. Because a was the key, it returns b, the value.

But what about the other way around? If we want to grab a, there is no easy way to do so. An Iterator would have to be used to manually iterate through all the elements and check if each value matches b. If a match is found, then it would return a.

This however, is a poor design. Why should it be easy to get one end location of the link, and hard to get the other? Again, a Link only stores two locations. Simply having two locations as instance variables isn't hard to implement, and it would be a better design and make accessing each location much simpler.

**Comment by ghost** [comment]
You don't need to access location key b. You only need a. 

Ex. minesweeper game
The start (a) doesn't link anywhere, but others (a) link to start (b). You don't need to know who links to start, that is unnecessary. All you need to know is that you're at the start. When you are at "a", you go to "b". That's it. EASY. SIMPLE. THAT'S IT

**Comment by nt314p** [comment]
It makes sense!!

**Comment by nt314p** [comment]
It makes sense!!
