### ISSUE TITLE
Why are the descriptions for Items stored in an arraylist?

### ISSUE THREAD

**Issue by nt314p** [nt314p/Zork#3]
I don't see the point of having multiple descriptions for an item. Possibly you could have a short description or long description but why would you need more than a few?

**Comment by ghost** [comment]
Ex. you could have green, medium, circular

Accepted could be green, blue, orange, medium, large, circular, square
If all item descriptions are in the accepted then you're good.

**Comment by nt314p** [comment]
But in what situation would we need all of these descriptions?

**Comment by ghost** [comment]
I don't know, it might just be helpful.
