### ISSUE TITLE
Room shouldn't store its sides

### ISSUE THREAD

**Issue by ghost** [nt314p/Zork#5]
A room's sides are stored in the map, by getting the side with coords + 0.5. Storing sides requires more inputted work than simply inputting the side into the mapLoader.

**Comment by nt314p** [comment]
Ben, it's one of my hunches. I think that it would be useful for rooms to store their sides because it makes since, and things that make sense make my parser happy. Currently, we have: getting the room, searching itself up in the master map, and then getting its sides.
