### ISSUE TITLE
Where are characters' locations stored?

### ISSUE THREAD

**Issue by ghost** [nt314p/Zork#6]
The player's location is stored in the **map**, which is in the **phase**, which is in the **game**.  As of right now I added other characters into non-static "player", but this doesn't allow for storing a location of them and for movement.

Would it be better to have a seperate "character" class storing their location and movement?

**Comment by nt314p** [comment]
I think that we should create a Character class and make the Player class a child of the Character class.

This would allow the creation of characters without special abilities/things that the player has

**Comment by ghost** [comment]
I agree with that - but where are the locations stored? I came up with two options - which do you like more @nt314p?

1. We could move the locations into the character, in a coordinate system.
2. We keep player's location dispersed through game, phase, map, etc, while characters are stored in the room's inventory (as it would store an item).
